<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\GliderUI.Server\Server.props" />
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <GliderUIGenerator_GenerateTypeMapping>GliderUI.Server</GliderUIGenerator_GenerateTypeMapping>
  </PropertyGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\GliderUI.Common\GliderUI.Common.csproj" />
    <ProjectReference Include="..\GliderUI.Generator\RpcUIShell.Generator.csproj">
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="GliderUIGenerator_GenerateTypeMapping" />
    <AdditionalFiles Include="..\GliderUI.ApiExporter\Api.xml" />
  </ItemGroup>
</Project>
