<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\GliderUI.Server\Server.props" />
  <ItemGroup>
    <ProjectReference Include="..\RpcUIShell.Core\RpcUIShell.Core.csproj" />
    <Compile Include="..\GliderUI.Server\System\DataSource.cs" Link="ServerTypes\DataSource.cs" />
    <Compile Include="..\GliderUI.Server\System\DataSourceTypeInfo.cs" Link="ServerTypes\DataSourceTypeInfo.cs" />
    <Compile Include="..\GliderUI.Server\System\DataSourcePropertyInfo.cs" Link="ServerTypes\DataSourcePropertyInfo.cs" />
    <Compile Include="..\GliderUI.Server\System\DataSourcePropertyComparer.cs" Link="ServerTypes\DataSourcePropertyComparer.cs" />
  </ItemGroup>
</Project>
