using Microsoft.CodeAnalysis;
using RpcUIShell.Core;

namespace RpcUIShell.Generator;

internal static class EnumGenerator
{
    public static void Generate(SourceProductionContext sourceProductionContext)
    {
        Api api = Generator.Api!;

        foreach (var enumDef in api.Enums)
        {
            var codeWriter = new CodeWriter();

            var ns = Generator.GetTargetNamespace(enumDef.Namespace);

            codeWriter.Append($$"""
                // <auto-generated/>

                namespace {{ns}};

                public enum {{enumDef.Name}} : global::System.{{enumDef.UnderlyingType}}
                {
                """);

            codeWriter.IncrementIndent();
            foreach (var item in enumDef.Entries)
            {
                codeWriter.Append($"{item.Name} = {item.Value},");
            }
            codeWriter.DecrementIndent();

            codeWriter.Append("}");

            sourceProductionContext.AddSource($"{api.ModuleName}.{enumDef.Namespace}.{enumDef.Name}.g.cs", codeWriter.ToString());
        }
    }

    public static void GenerateTypeMapping(
        SourceProductionContext sourceProductionContext,
        string rootNamespace)
    {
        Api api = Generator.Api!;
        var codeWriter = new CodeWriter();

        codeWriter.Append($$"""
            // <auto-generated/>
            #nullable enable
            using RpcUIShell.Core;

            namespace {{rootNamespace}};

            internal static partial class TypeMappingInitializer
            {
            """);

        codeWriter.IncrementIndent();
        codeWriter.AppendAndReserveNewLine($$"""
            private static void InitEnumTypeMapping()
            {
                EnumTypeMapping.Get().InitMapping(_enumList);
            }
            """);

        codeWriter.Append($$"""
            private static readonly List<(string, string)> _enumList = [
            """);

        codeWriter.IncrementIndent();
        foreach (var enumDef in api.Enums)
        {
            var ns = Generator.GetTargetNamespace(enumDef.Namespace);
            codeWriter.Append($"""
                ("{ns}.{enumDef.Name}, {api.ModuleName}", "{enumDef.FullName}"),
                """);
        }
        codeWriter.DecrementIndent();

        codeWriter.Append("];");

        codeWriter.DecrementIndent();
        codeWriter.Append("}");

        sourceProductionContext.AddSource($"EnumTypeMappingInitializer.g.cs", codeWriter.ToString());
    }
}
