using Microsoft.CodeAnalysis;
using RpcUIShell.Core;

namespace RpcUIShell.Generator;

internal static class ObjectGenerator
{
    private static readonly Dictionary<string, ObjectDef> _objectDefs = [];

    public static void Generate(SourceProductionContext sourceProductionContext)
    {
        CreateObjectDefMap();

        foreach (var keyValuePair in _objectDefs)
        {
            ObjectDef objectDef = keyValuePair.Value;
            string filename = objectDef.GetSourceCodeFileName();
            string sourceCode = objectDef.Generate();
            sourceProductionContext.AddSource(filename, sourceCode);
        }

        DestroyObjectDefMap();
    }

    private static void CreateObjectDefMap()
    {
        Api api = Generator.Api!;

        foreach (var apiObjectDef in api.Objects)
        {
            ObjectDef objectDef = new(apiObjectDef);
            if (!objectDef.IsSupported())
                continue;

            var typeId = objectDef.Type.GetId();
            if (_objectDefs.ContainsKey(typeId))
            {
                DestroyObjectDefMap();
                throw new InvalidOperationException($"Duplicate object found: {typeId}");
            }
            _objectDefs[typeId] = objectDef;
        }
    }

    private static void DestroyObjectDefMap()
    {
        _objectDefs.Clear();
    }

    public static ObjectDef? GetObjectDef(TypeDef typeDef)
    {
        var typeId = typeDef.GetId();
        if (_objectDefs.TryGetValue(typeId, out var objectDef))
        {
            return objectDef;
        }
        return null;
    }

    public static void GenerateTypeMapping(
        SourceProductionContext sourceProductionContext,
        string rootNamespace)
    {
        Api api = Generator.Api!;
        var codeWriter = new CodeWriter();

        codeWriter.Append($$"""
            // <auto-generated/>
            #nullable enable
            using RpcUIShell.Core;

            namespace {{rootNamespace}};

            internal static partial class TypeMappingInitializer
            {
            """);

        codeWriter.IncrementIndent();
        codeWriter.AppendAndReserveNewLine($$"""
            private static void InitObjectTypeMapping()
            {
                ObjectTypeMapping.Get().InitMapping(_objectList);
            }
            """);

        codeWriter.Append($$"""
            private static readonly List<(string, string)> _objectList = [
            """);

        codeWriter.IncrementIndent();

        foreach (var (systemTypeFullName, _) in Api.SystemTypes)
        {
            codeWriter.Append($"""
                ("{systemTypeFullName}, System.Private.CoreLib", "{systemTypeFullName}, System.Private.CoreLib"),
                """);
        }

        foreach (var apiTypeMappingDef in api.TypeMappings)
        {
            var targetTypeFullName = Generator.GetTargetTypeFullName(apiTypeMappingDef.FullName);

            codeWriter.Append($"""
                ("{targetTypeFullName}", "{apiTypeMappingDef.FullName}"),
                """);
        }

        foreach (var apiObjectDef in api.Objects)
        {
            ObjectDef objectDef = new(apiObjectDef);
            if (!objectDef.IsSupported())
                continue;

            var targetTypeFullName = Generator.GetTargetTypeFullName(apiObjectDef.FullName);

            codeWriter.Append($"""
                ("{targetTypeFullName}", "{apiObjectDef.FullName}"),
                """);

            if (apiObjectDef.NestedTypes is null)
                continue;

            foreach (var nestedApiObjectDef in apiObjectDef.NestedTypes)
            {
                ObjectDef nestedObjectDef = new(nestedApiObjectDef);
                if (!nestedObjectDef.IsSupported())
                    continue;

                var nestedTargetTypeFullName = Generator.GetTargetTypeFullName(nestedApiObjectDef.FullName);
                codeWriter.Append($"""
                    ("{nestedTargetTypeFullName}", "{nestedApiObjectDef.FullName}"),
                    """);
            }
        }
        codeWriter.DecrementIndent();

        codeWriter.Append("];");

        codeWriter.DecrementIndent();
        codeWriter.Append("}");

        sourceProductionContext.AddSource($"ObjectTypeMappingInitializer.g.cs", codeWriter.ToString());
    }
}
